Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'application#check_account_exists'
  resources :category, :only => [:create, :destroy], defaults: { format: 'json' }
  get '/category' , :to => 'category#index'
  get "/category/products" , :to => 'category#get_product'
  post '/category/create', :to => 'category#create'
  post '/category/add_product', :to => 'category#add_product'
  put '/product/update' , :to => 'category#edit'
  delete '/product/delete', :to => 'category#destroy'
  post '/delivery/agency' , :to => 'delivery#create'
  put '/delivery_agency/update',:to => 'delivery#edit'
  delete '/delivery_agency/delete' , :to => 'delivery#destroy'
  get '/delivery/agency' , :to => 'delivery#index'
  put '/delivery/edit_agency' , :to => 'delivery#edit_agency'
  post '/delivery/agent' , :to => 'delivery#create_agent'
  get '/delivery/agent' , :to => 'delivery#get_agents'
  put '/delivery_agent/update' , :to => 'delivery#edit_agent'
  get '/delivery/agent_all', :to => 'delivery#get_all_agents'
  post '/orders/create' , :to => 'order#create'
  get '/orders/index', :to => 'order#index'
  put '/orders/edit', :to => 'order#edit'
  delete '/order/delete' , :to => 'order#destroy'
  post '/vendor/create', :to => 'vendor#create'
  get '/vendor/get_vendors', :to => 'vendor#index'
  put '/vendor/update' , :to => 'vendor#edit'
  delete '/vendor/delete', :to => 'vendor#destroy'
  post '/stock/create', :to => 'vendor#create_stock'
  get '/stock/get_stocks', :to => 'vendor#get_stocks'
  put '/stock/update_stock', :to => 'vendor#edit_stock'
  delete '/stock/destroy', :to => 'vendor#destroy_stock'
  get '/customer/index', :to => 'customer#index'
  get '/index/reports', :to => 'report#index'
end
